name: format

on: [push, pull_request]

jobs:
  format:

    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install autopep8

    - name: Format code
      run: |
        autopep8 .

    - name: Check code changes
      run: |
        git diff --exit-code
        if ( $? -ne 0 )
        {
          exit 1
        }
